name: remote ssh && git pull
on:
  push:
    branches:
      - gh-pages
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /usr/share/nginx/shuai08 && git pull 
          cd /usr/share/nginx/shuai08/shuai08 && git pull 